// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvpnammMIdoFYO-I-NG53WkkukBHzV2o0',
    appId: '1:579236992295:web:f3086ac2c4f2c6f1430502',
    messagingSenderId: '579236992295',
    projectId: 'fir-flutter-codelab-70c44',
    authDomain: 'fir-flutter-codelab-70c44.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-70c44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2fj-HAilwdC25ugFlaESMQ7TFRV7_Bow',
    appId: '1:579236992295:android:405054c0cb07ae1c430502',
    messagingSenderId: '579236992295',
    projectId: 'fir-flutter-codelab-70c44',
    storageBucket: 'fir-flutter-codelab-70c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAs9RV90C6HdU8OajToQK4kZwXRDNebdY',
    appId: '1:579236992295:ios:65bde64a4ca8d103430502',
    messagingSenderId: '579236992295',
    projectId: 'fir-flutter-codelab-70c44',
    storageBucket: 'fir-flutter-codelab-70c44.appspot.com',
    iosClientId: '579236992295-gqgdmcnss88rmbgljhm3fqjjd85d5km5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAs9RV90C6HdU8OajToQK4kZwXRDNebdY',
    appId: '1:579236992295:ios:65bde64a4ca8d103430502',
    messagingSenderId: '579236992295',
    projectId: 'fir-flutter-codelab-70c44',
    storageBucket: 'fir-flutter-codelab-70c44.appspot.com',
    iosClientId: '579236992295-gqgdmcnss88rmbgljhm3fqjjd85d5km5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
